const ExtractData = [
  {
    id: 1,
    operacao: "Pagamento efetuado",
    tipo: "debito",
    dataOperacao: "2022-05-02",
    icone: "boleto",
    valor: 5500.5,
    destinatario: "Banco Inter",
  },
  {
    id: 2,
    operacao: "Transação Recebida",
    tipo: "credito",
    dataOperacao: "2022-05-10",
    icone: "ted",
    valor: 10500.5,
    destinatario: "",
    remetente: "Avanade",
  },
  {
    id: 3,
    operacao: "Transação efetuada",
    tipo: "debito",
    dataOperacao: "2022-05-15",
    icone: "pix",
    valor: 1000.0,
    destinatario: "C6 Bank",
    remetente: "",
  },
  {
    id: 4,
    operacao: "Pagamento efetuado",
    tipo: "credito",
    dataOperacao: "2022-05-20",
    icone: "boleto",
    valor: 500.0,
    destinatario: "",
    remetente: "",
  },
  {
    id: 2,
    operacao: "Transação Recebida",
    tipo: "credito",
    dataOperacao: "2022-05-10",
    icone: "ted",
    valor: 10500.5,
    destinatario: "",
    remetente: "Avanade",
  },
];

export default ExtractData;
